backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: 'sections'
    label: 'Sections'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Full name', name: 'fullName', widget: 'string' }
          - {
              label: 'Greeting text',
              name: 'greeting',
              widget: 'string',
              hint: 'Displayed above the full name',
            }
