backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img # Media files will be stored in the repo under public/img
public_folder: img
collections:
  - name: 'sections'
    label: 'Sections'
    files:
      - label: 'Hero'
        name: 'hero'
        file: 'src/content/sections/hero.md'
        fields:
          - label: 'Display picture'
            name: 'avatar'
            widget: 'image'
            required: false
          - {
              label: 'Greeting text',
              name: 'greeting',
              widget: 'string',
              hint: 'Displayed above the full name',
            }
          - { label: 'Full name', name: 'fullName', widget: 'string' }
          - label: 'Nickname text'
            name: 'nicknameText'
            widget: 'object'
            fields:
              - {
                  label: 'Nickname intro',
                  name: 'nicknameIntro',
                  widget: 'string',
                }
              - {
                  label: 'Nickname value',
                  name: 'nicknameValue',
                  widget: 'string',
                }
          - {
              label: 'Description',
              name: 'description',
              widget: 'text',
              hint: 'More information about what you do. Placed below the nickname.',
            }
          - label: 'Important words in the description'
            name: 'highlightedWords'
            widget: 'list'
            hint: 'Words in the description field that should be highlighted'
          - {
              label: 'Projects section CTA text',
              name: 'projectsCTA',
              widget: 'string',
              hint: 'Displayed in the primary button',
            }
          - {
              label: 'Contacts section CTA text',
              name: 'contactsCTA',
              widget: 'string',
              hint: 'Displayed in the secondary button',
            }
      - label: 'About'
        name: 'about'
        file: 'src/content/sections/about.md'
        fields:
          - label: 'Section title'
            name: 'sectionTitle'
            widget: 'string'
          - label: 'About content cards'
            name: 'aboutCard'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Important words in the description'
                name: 'highlightedWords'
                widget: 'list'
                hint: 'Words in the description field that should be highlighted'
          - label: 'Download CV area'
            name: 'downloadCV'
            widget: 'object'
            fields:
              - {
                  label: 'Download CV description',
                  name: 'description',
                  widget: 'text',
                }
              - {
                  label: 'Download CV button CTA',
                  name: 'buttonCTAText',
                  widget: 'string',
                }
              - {
                  label: 'CV file',
                  name: 'cvFile',
                  widget: 'file',
                  media_folder: '/public/files',
                }
      - label: 'Skills'
        name: 'skills'
        file: 'src/content/sections/skills.md'
        fields:
          - label: 'Section title'
            name: 'sectionTitle'
            widget: 'string'
          - label: 'Skills groups'
            name: 'skillsGroup'
            widget: 'list'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Skills list'
                name: 'skillsList'
                widget: 'list'
                fields:
                  - { label: 'Label', name: 'label', widget: 'string' }
                  - { label: 'Icon', name: 'icon', widget: 'image' }
      - label: 'Projects'
        name: 'projects'
        file: 'src/content/sections/projects.md'
        fields:
          - label: 'Section title'
            name: 'sectionTitle'
            widget: 'string'
          - label: 'List of projects'
            name: 'projectsList'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Important words in the description'
                name: 'highlightedWords'
                widget: 'list'
                hint: 'Words in the description field that should be highlighted'
              - label: 'Technology stack'
                name: 'techStack'
                widget: 'list'
                hint: 'List of technology tools used in creating this project'
              - {
                  label: 'View project website CTA text',
                  name: 'viewProjectCTA',
                  widget: 'string',
                  hint: 'Displayed in a primary button',
                }
              - {
                  label: 'View project source code CTA text',
                  name: 'viewSourceCodeCTA',
                  widget: 'string',
                  hint: 'Displayed in a secondary button',
                }
  - name: 'components'
    label: 'Components'
    files:
      - label: 'Logo'
        name: 'logo'
        file: 'src/content/components/logo.md'
        fields:
          - label: 'Logo image'
            name: 'src'
            widget: 'image'
          - label: 'Default alt text'
            name: 'defaultAltText'
            widget: 'string'
      - label: 'Nav Links'
        name: 'navLinks'
        file: 'src/content/components/navLinks.md'
        fields:
          - label: 'Nav links list'
            name: 'navLinks'
            widget: 'list'
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'Link URL', name: 'link', widget: 'string' }
      - label: 'Social Links'
        name: 'socialLinks'
        file: 'src/content/components/socialLinks.md'
        fields:
          - label: 'Social links list'
            name: 'socialLinks'
            widget: 'list'
            fields:
              - {
                  label: 'Title',
                  name: 'title',
                  widget: 'string',
                  hint: 'Displayed when icon is hovered',
                }
              - label: 'Icon name'
                name: 'name'
                widget: 'select'
                hint: 'Icon name'
                options:
                  - { label: 'Github', value: 'github' }
                  - { label: 'Gmail', value: 'gmail' }
                  - { label: 'Linkedin', value: 'linkedin' }
              - { label: 'Link URL', name: 'link', widget: 'string' }
  - name: 'layout'
    label: 'Layout'
    files:
      - label: 'Footer'
        name: 'footer'
        file: 'src/content/layout/footer.md'
        fields:
          - label: 'Footer quote'
            name: 'footerQuote'
            widget: 'text'
          - label: 'Copyright text'
            name: 'copyrightText'
            widget: 'object'
            fields:
              - { label: 'Line 1', name: 'line1', widget: 'string' }
              - { label: 'Line 2', name: 'line2', widget: 'string' }
